(() => {
  'use strict';
  const STORAGE = 'fxness-paper-v1';
  const quotes = {
    'EUR/USD': { bid: 1.0842, ask: 1.0844, change: '+0.42%', decimals: 4 },
    'GBP/USD': { bid: 1.2638, ask: 1.2641, change: '-0.18%', decimals: 4 },
    'USD/JPY': { bid: 151.62, ask: 151.65, change: '+0.27%', decimals: 2 },
    'XAU/USD': { bid: 2164.80, ask: 2165.25, change: '+0.64%', decimals: 2 }
  };
  const state = { user: null, currentRoute: 'dashboard', selectedMarket: 'EUR/USD', direction: 'buy', sidebarOpen: false };
  const $ = (selector, root = document) => root.querySelector(selector);
  const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
  const money = value => `$${Number(value || 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
  const quote = (market, side = 'bid') => Number(quotes[market]?.[side] || 0);
  const load = () => { try { return JSON.parse(localStorage.getItem(STORAGE)) || { users: [], session: null }; } catch { return { users: [], session: null }; } };
  const save = data => localStorage.setItem(STORAGE, JSON.stringify(data));
  const db = () => load();
  const currentUser = () => { const data = db(); return data.users.find(user => user.id === data.session) || null; };
  const initials = name => (name || 'Trader').split(' ').map(word => word[0]).join('').slice(0, 2).toUpperCase();
  const notify = (message, type = 'normal') => { const toast = $('#toast'); toast.textContent = message; toast.className = `toast show ${type}`; setTimeout(() => { toast.className = 'toast'; }, 3000); };
  const show = (id, visible) => $(id).classList.toggle('hidden', !visible);
  function renderShell() {
    state.user = currentUser();
    show('#landing-view', !state.user);
    show('#auth-view', false);
    show('#app-view', !!state.user);
    if (state.user) { updateIdentity(); renderRoute(state.currentRoute); } else { bindPublicRoutes(); }
  }
  function updateIdentity() {
    const name = state.user.name || 'Trader'; const initial = initials(name);
    $('#sidebar-name').textContent = name; $('#user-avatar').textContent = initial; $('#header-avatar').textContent = initial;
  }
  function showAuth(mode) { show('#landing-view', false); show('#app-view', false); show('#auth-view', true); show('#login-form-wrap', mode === 'login'); show('#register-form-wrap', mode === 'register'); window.scrollTo(0, 0); }
  function bindPublicRoutes() { $$('[data-public-route]').forEach(link => link.onclick = event => { event.preventDefault(); const target = link.dataset.publicRoute; if (target === 'markets' || target === 'features' || target === 'home') document.getElementById(target)?.scrollIntoView({ behavior: 'smooth' }); }); }
  function userData() { return state.user; }
  function persistUser(updated) { const data = db(); const index = data.users.findIndex(user => user.id === updated.id); if (index >= 0) data.users[index] = updated; save(data); state.user = updated; }
  function renderRoute(route) {
    state.currentRoute = route; const content = $('#app-content'); const titles = { dashboard: 'Overview', markets: 'Markets', trade: 'Trade', positions: 'Positions', transactions: 'Transactions', profile: 'Profile', settings: 'Settings' }; $('#page-title').textContent = titles[route] || 'Overview';
    $$('.side-nav button[data-route]').forEach(btn => btn.classList.toggle('active', btn.dataset.route === route));
    if (route === 'dashboard') content.innerHTML = dashboardTemplate();
    if (route === 'markets') content.innerHTML = marketsTemplate();
    if (route === 'trade') content.innerHTML = tradeTemplate();
    if (route === 'positions') content.innerHTML = positionsTemplate();
    if (route === 'transactions') content.innerHTML = transactionsTemplate();
    if (route === 'profile') content.innerHTML = profileTemplate();
    if (route === 'settings') content.innerHTML = settingsTemplate();
    state.sidebarOpen = false; $('#sidebar').classList.remove('open'); bindAppEvents();
  }
  const header = (eyebrow, title, sub, action = '') => `<div class="page-heading"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p>${sub}</p></div>${action}</div>`;
  function statsTemplate() { const positions = userData().positions || []; const pnl = positions.reduce((sum, p) => sum + livePnl(p), 0); return `<div class="stat-grid"><div class="dashboard-card stat-card"><span class="card-label">Account balance <span>◉</span></span><b class="stat-value">${money(userData().balance)}</b><span class="stat-sub">Paper funds</span></div><div class="dashboard-card stat-card"><span class="card-label">Available balance <span>◈</span></span><b class="stat-value">${money(userData().balance)}</b><span class="stat-sub">No margin used</span></div><div class="dashboard-card stat-card"><span class="card-label">Open positions <span>◒</span></span><b class="stat-value">${positions.length}</b><span class="stat-sub">Active paper trades</span></div><div class="dashboard-card stat-card"><span class="card-label">Total P/L <span>↗</span></span><b class="stat-value ${pnl >= 0 ? 'positive' : 'negative'}">${pnl >= 0 ? '+' : ''}${money(pnl)}</b><span class="stat-sub">Unrealized</span></div></div>`; }
  function dashboardTemplate() { return header('OVERVIEW', `Good ${new Date().getHours() < 12 ? 'morning' : 'afternoon'}, ${userData().name.split(' ')[0]}`, 'Here is your paper-trading snapshot.', '<button class="btn btn-primary" data-route="trade">＋ Open a trade</button>') + statsTemplate() + `<div class="content-grid"><section class="content-card"><div class="card-head"><h3>Recent transactions</h3><button class="text-link" data-route="transactions">View all</button></div>${transactionRows((userData().transactions || []).slice(-5).reverse())}</section><section class="content-card"><div class="card-head"><h3>Market overview</h3><button class="text-link" data-route="markets">View markets</button></div>${marketRows()}</section></div>`; }
  function marketRows() { return `<div class="table-wrap"><table><thead><tr><th>Market</th><th>Bid</th><th>Change</th></tr></thead><tbody>${Object.entries(quotes).map(([name, q]) => `<tr><td class="instrument">${name}<small>Forex / Metals</small></td><td>${q.bid.toFixed(q.decimals)}</td><td class="${q.change[0] === '+' ? 'positive' : 'negative'}">${q.change}</td></tr>`).join('')}</tbody></table></div>`; }
  function transactionRows(rows) { if (!rows.length) return '<div class="empty-state"><strong>No transactions yet</strong>Your paper-trading activity will appear here.</div>'; return `<div class="table-wrap"><table><thead><tr><th>Activity</th><th>Type</th><th>Amount</th></tr></thead><tbody>${rows.map(t => `<tr><td>${t.label}<small class="muted">${new Date(t.date).toLocaleDateString()}</small></td><td><span class="pill">${t.type}</span></td><td class="${t.amount >= 0 ? 'positive' : ''}">${t.amount >= 0 ? '+' : ''}${money(t.amount)}</td></tr>`).join('')}</tbody></table></div>`; }
  function marketsTemplate() { return header('MARKET WATCH', 'Markets', 'Explore simulated quotes and choose an instrument to practice.') + `<div class="market-list">${Object.entries(quotes).map(([name, q]) => `<article class="market-card"><div><h3>${name}</h3><p>${q.change} today · Simulated</p></div><div class="quote"><div>Bid<b>${q.bid.toFixed(q.decimals)}</b></div><div>Ask<b>${q.ask.toFixed(q.decimals)}</b></div></div><div class="market-actions"><button class="small-btn buy-btn" data-quick-trade="${name}" data-direction="buy">Buy</button><button class="small-btn sell-btn" data-quick-trade="${name}" data-direction="sell">Sell</button></div></article>`).join('')}</div>`; }
  function tradeTemplate() { const q = quotes[state.selectedMarket]; return header('PAPER TRADING', 'Open a trade', 'Practice a setup with predefined risk levels.') + `<div class="trade-layout"><section class="trade-panel"><h2>Trade ticket</h2><p>All orders are simulated and use no real funds.</p><div class="direction-toggle"><button class="${state.direction === 'buy' ? 'selected buy' : ''}" data-direction="buy">Buy / Long</button><button class="${state.direction === 'sell' ? 'selected sell' : ''}" data-direction="sell">Sell / Short</button></div><label class="form-label">Market<select id="trade-market" class="form-select">${Object.keys(quotes).map(m => `<option ${m === state.selectedMarket ? 'selected' : ''}>${m}</option>`).join('')}</select></label><div class="form-row"><label class="form-label">Trade amount<input class="form-input" id="trade-amount" type="number" min="1" step="0.01" value="1000"></label><label class="form-label">Entry price<input class="form-input" id="trade-entry" type="number" step="0.0001" value="${q[state.direction === 'buy' ? 'ask' : 'bid']}"></label></div><div class="form-row"><label class="form-label">Stop-loss <input class="form-input" id="trade-sl" type="number" step="0.0001" placeholder="Optional"></label><label class="form-label">Take-profit <input class="form-input" id="trade-tp" type="number" step="0.0001" placeholder="Optional"></label></div><div class="trade-note">ⓘ Paper orders are for educational testing only. No real money is involved.</div><button class="btn btn-primary btn-full" data-action="open-trade">Open paper trade</button></section><section class="trade-panel"><div class="card-head"><div><h2>Open positions</h2><p style="margin:5px 0 0">Your active paper trades</p></div></div>${positionsTable(userData().positions || [], true)}</section></div>`; }
  function livePnl(p) { const diff = quote(p.instrument, p.direction === 'buy' ? 'bid' : 'ask') - p.entry; return (p.direction === 'buy' ? diff : -diff) * p.amount; }
  function positionsTable(positions, compact = false) { if (!positions.length) return '<div class="empty-state"><strong>No open positions</strong>Select a market to begin paper trading.</div>'; return `<div class="table-wrap"><table><thead><tr><th>Instrument</th><th>Side</th><th>Amount</th><th>Entry</th><th>Current</th><th>P/L</th><th></th></tr></thead><tbody>${positions.map(p => { const pnl = livePnl(p); return `<tr><td class="instrument">${p.instrument}</td><td><span class="pill ${p.direction}">${p.direction.toUpperCase()}</span></td><td>${money(p.amount)}</td><td>${p.entry}</td><td>${quote(p.instrument, p.direction === 'buy' ? 'bid' : 'ask').toFixed(quotes[p.instrument].decimals)}</td><td class="${pnl >= 0 ? 'positive' : 'negative'}">${pnl >= 0 ? '+' : ''}${money(pnl)}</td><td><button class="text-link" data-close-position="${p.id}">Close</button></td></tr>`; }).join('')}</tbody></table></div>`; }
  function positionsTemplate() { return header('PORTFOLIO', 'Open positions', 'Monitor and close your active paper trades.') + `<section class="content-card">${positionsTable(userData().positions || [])}</section>`; }
  function transactionsTemplate() { return header('ACTIVITY', 'Transactions', 'A record of simulated trading activity.') + `<section class="content-card">${transactionRows((userData().transactions || []).slice().reverse())}</section>`; }
  function profileTemplate() { return header('ACCOUNT', 'Profile', 'Manage your paper account details.') + `<section class="content-card"><div class="profile-hero"><span class="avatar">${initials(userData().name)}</span><div><h2>${userData().name}</h2><p>${userData().email}</p><span class="success-badge">● Active paper account</span></div></div><div class="profile-fields"><div class="setting-row"><h4>Full name</h4><span>${userData().name}</span></div><div class="setting-row"><h4>Email</h4><span>${userData().email}</span></div><div class="setting-row"><h4>Account type</h4><span>Paper trading</span></div><div class="setting-row"><h4>Balance</h4><span>${money(userData().balance)}</span></div></div><button class="btn btn-ghost" data-action="logout" style="margin-top:25px">Log out</button></section>`; }
  function settingsTemplate() { const settings = userData().settings || { dark: true, notifications: true }; return header('PREFERENCES', 'Settings', 'Personalize your FXNESS workspace.') + `<div class="settings-grid"><section class="content-card"><h3>Appearance & notifications</h3><div class="setting-row"><div><h4>Dark appearance</h4><p>Use the focused dark workspace.</p></div><button class="toggle ${settings.dark ? 'on' : ''}" data-setting="dark"><i></i></button></div><div class="setting-row"><div><h4>Notifications</h4><p>Receive practice reminders.</p></div><button class="toggle ${settings.notifications ? 'on' : ''}" data-setting="notifications"><i></i></button></div></section><section class="content-card"><h3>Account settings</h3><div class="setting-row"><div><h4>Currency</h4><p>Display currency for this prototype.</p></div><strong>USD</strong></div><div class="setting-row"><div><h4>Data storage</h4><p>Saved locally in this browser.</p></div><span class="success-badge">Local only</span></div></section></div>`; }
  function bindAppEvents() { $$('[data-route]').forEach(el => el.onclick = e => { e.preventDefault(); renderRoute(el.dataset.route); }); $$('[data-direction]').forEach(el => el.onclick = () => { if (el.dataset.direction) { state.direction = el.dataset.direction; if ($('#app-content')) renderRoute('trade'); } }); $('#trade-market')?.addEventListener('change', e => { state.selectedMarket = e.target.value; renderRoute('trade'); }); $$('[data-quick-trade]').forEach(el => el.onclick = () => { state.selectedMarket = el.dataset.quickTrade; state.direction = el.dataset.direction; renderRoute('trade'); }); $$('[data-close-position]').forEach(el => el.onclick = () => closePosition(el.dataset.closePosition)); $('[data-action="open-trade"]')?.addEventListener('click', openTrade); $$('[data-setting]').forEach(el => el.onclick = () => { const updated = { ...userData(), settings: { ...(userData().settings || {}), [el.dataset.setting]: !(userData().settings || {})[el.dataset.setting] } }; persistUser(updated); renderRoute('settings'); }); $$('[data-action="logout"]').forEach(el => el.onclick = logout); updatePositionCount(); }
  function updatePositionCount() { const count = (userData()?.positions || []).length; $('#position-count').textContent = count; }
  function openTrade() { const amount = Number($('#trade-amount').value); const entry = Number($('#trade-entry').value); if (!amount || amount <= 0 || !entry || entry <= 0) return notify('Enter a valid amount and entry price.', 'error'); const user = userData(); const position = { id: crypto.randomUUID ? crypto.randomUUID() : String(Date.now()), instrument: state.selectedMarket, direction: state.direction, amount, entry, stop: Number($('#trade-sl').value) || null, target: Number($('#trade-tp').value) || null, date: new Date().toISOString() }; user.positions = [...(user.positions || []), position]; user.transactions = [...(user.transactions || []), { label: `${state.direction === 'buy' ? 'Buy' : 'Sell'} ${state.selectedMarket}`, type: 'Trade', amount: 0, date: position.date }]; persistUser(user); notify('Paper trade opened.', 'success'); renderRoute('positions'); }
  function closePosition(id) { const user = userData(); const position = (user.positions || []).find(p => p.id === id); if (!position) return; const pnl = livePnl(position); user.positions = user.positions.filter(p => p.id !== id); user.transactions = [...(user.transactions || []), { label: `Closed ${position.direction} ${position.instrument}`, type: 'Trade close', amount: pnl, date: new Date().toISOString() }]; persistUser(user); notify('Paper position closed.', 'success'); renderRoute('positions'); }
  function logout() { const data = db(); data.session = null; save(data); state.user = null; state.currentRoute = 'dashboard'; renderShell(); notify('You have been logged out.'); }
  document.addEventListener('click', event => { const action = event.target.closest('[data-action]')?.dataset.action; if (action === 'show-login') showAuth('login'); if (action === 'show-register') showAuth('register'); if (action === 'show-landing') renderShell(); if (action === 'toggle-sidebar') { state.sidebarOpen = !state.sidebarOpen; $('#sidebar').classList.toggle('open', state.sidebarOpen); } if (action === 'toggle-public-menu') $('.public-nav').classList.toggle('mobile-open'); });
  $('#login-form').addEventListener('submit', event => { event.preventDefault(); const data = db(); const user = data.users.find(item => item.email.toLowerCase() === $('#login-email').value.trim().toLowerCase() && item.password === $('#login-password').value); if (!user) return notify('Incorrect email or password.', 'error'); data.session = user.id; save(data); state.user = user; renderShell(); notify('Welcome back.', 'success'); });
  $('#register-form').addEventListener('submit', event => { event.preventDefault(); const name = $('#register-name').value.trim(); const email = $('#register-email').value.trim().toLowerCase(); const password = $('#register-password').value; if (password !== $('#register-confirm').value) return notify('Passwords do not match.', 'error'); const data = db(); if (data.users.some(user => user.email === email)) return notify('An account with that email already exists.', 'error'); const user = { id: crypto.randomUUID ? crypto.randomUUID() : String(Date.now()), name, email, password, balance: 0, positions: [], transactions: [], settings: { dark: true, notifications: true } }; data.users.push(user); data.session = user.id; save(data); state.user = user; renderShell(); notify('Account created with a $0.00 balance.', 'success'); });
  renderShell();
})();
